### PR TITLE
do not hide webpack errors

### LINKED ISSUE #4: webpack errors/warnings are hidden
packaging should fail on webpack build erros/warnings

### PR DESCRIPTION
**Pull request by akleiber**
fixes #4

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -20,6 +20,22 @@ class ServerlessPluginWebpack {
...
+          colors: true
+        })
+        console.log('[webpack:build]', stringStats)
+
+        if (jsonStats.errors.length > 0) {
+          reject('webpack failed')
+        }
+
+        if(jsonStats.warnings.length > 0) {
+          reject('webpack failed')
```
Comment (robdasilva) [inline index.js]: Theoretically not, but I understand the thinking behind it and for now this probably makes the most sense.

**Review by robdasilva — APPROVED** [review]
